server:
  port: 9092

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-port: 8761
    serviceUrl:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka

spring:
  application:
    name: email-service
  mvc:
    servlet:
      load-on-startup: 1
